# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_CAMPAIGNFACTORY_ADDRESS_CRONOS: ${{ secrets.REACT_APP_CAMPAIGNFACTORY_ADDRESS_CRONOS }}
      REACT_APP_NETWORKID_CRONOS: ${{ secrets.REACT_APP_NETWORKID_CRONOS }}
      REACT_APP_RPC_CRONOS: ${{ secrets.REACT_APP_RPC_CRONOS }}
      REACT_APP_MULTICALL_CRONOS: ${{ secrets.REACT_APP_MULTICALL_CRONOS }}
      REACT_APP_CAMPAIGNFACTORY_ADDRESS_ROPSTEN: ${{ secrets.REACT_APP_CAMPAIGNFACTORY_ADDRESS_ROPSTEN }}
      REACT_APP_RPC_ROPSTEN: ${{ secrets.REACT_APP_RPC_ROPSTEN }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
      
    - uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
